// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hujdolskefittayeiomq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1amRvbHNrZWZpdHRheWVpb21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODExNzUsImV4cCI6MjA2MDU1NzE3NX0.uKRfVv85HCg_RHxSP7mt1U9ook0-6i3W4qQluDrp-TY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);